### ISSUE TITLE
`ros-kineitc-*` is not supported on Debian 9.

### ISSUE THREAD

**Issue by acxz** [emlid/pi-gen-navio#5]
Based on the ROS's [REP 3](https://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021) ros-kinetic is not supported for Debian 9 (stretch), but ros-melodic is supported, [link](https://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023). As such I think it would be appropriate to move navio's ros version from ros-kinetic to ros-melodic.

**Comment by AlexanderDranitsa** [comment]
Hello @acxz!
Thanks for your report and sorry for the long response!
Could you please try out our [updated](https://community.emlid.com/t/raspberry-pi-os-with-8gb-raspberry-pi-4-support-is-here/21742) image and close the issue if it helps?

**Comment by acxz** [comment]
I'll go ahead and close this issue since the stretch image is not supported and the latest image should be used anyway.
